name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        auto-update-conda: true
        update-conda: true
        conda-channels: conda-forge

    - name: Conda install dependencies
      run: conda install python=${{ matrix.python-version }} pip nodejs=13 ipywidgets jupyter jupyterlab vtk flake8 pytest ipydatawidgets

    - name: Test flake8
      run: flake8 ipygany --ignore=E501

    - name: Install ipygany
      run: pip install -e .

    - name: Install labextension (Only on Ubuntu for build speed)
      if: matrix.os == 'ubuntu-latest'
      run: jupyter labextension install .

    - name: Run Python tests
      run: pytest tests

    - name: Build docs (Only on MacOS for build speed)
      if: matrix.os == 'macos-latest'
      run: |
           conda install sphinx sphinx_rtd_theme pygments==2.6.1 jupyter-sphinx meshpy pyvista
           cd docs/source/
           sphinx-build . _build/html
           cd ../..
